# Generated by Django 4.0.3 on 2022-04-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_couponusedusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-valid_to']},
        ),
    ]
