# Generated by Django 4.0.3 on 2022-04-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_logedin', models.BooleanField(default=False)),
            ],
        ),
    ]
