# Generated by Django 4.0.3 on 2022-04-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_productoffer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
