# Generated by Django 4.0.3 on 2022-04-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_categoryoffer_active_productoffer_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='is_logedin',
            new_name='is_logedinn',
        ),
    ]
