# Generated by Django 4.0.3 on 2022-04-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
